package ui;

import manager.FondoPanel;
import manager.GameManager;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author kgv17
 */
public class MainMenu extends javax.swing.JFrame {

    public JFrameFight frameFights;

    public MainMenu() {

        initComponents();
        setLocationRelativeTo(null);

        // ESTABLECER FUENTE AL BOTÓN Y EL TITULO
        try {

            Font pixelFont1 = Font.createFont(Font.TRUETYPE_FONT, new File(GameManager.font));
            Font pixelFont2 = Font.createFont(Font.TRUETYPE_FONT, new File(GameManager.fontBold));

            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(pixelFont1);

            this.jLabelTitulo1.setFont(pixelFont1.deriveFont(45f));
            this.jCheckBoxGame.setFont(pixelFont1.deriveFont(20f));
            this.jCheckBoxMusic.setFont(pixelFont1.deriveFont(20f));
            this.jButtonStart.setFont(pixelFont2.deriveFont(35f));
            this.jButtonStart.setHorizontalAlignment(SwingConstants.CENTER);
            this.jButtonStart.setVerticalAlignment(SwingConstants.CENTER);
            this.jButtonStart.setMargin(new Insets(100, 0, 0, 0));

        } catch (FontFormatException | IOException ex) {

            // EN CASO DE ERROR ESTABLECE ARIAL
            this.jLabelTitulo1.setFont(new Font("Arial", Font.PLAIN, 50));

        }

        // ESTABLECER ICONO AL FRAME
        try {

            Image imageIcon = ImageIO.read(new File(GameManager.icon));
            setIconImage(imageIcon);

        } catch (IOException e) {

            System.err.println("Error setting icon: " + e.getMessage());

        }

        // CARGAR Y ESCALAR LA IMAGEN DEL LABEL
        try {

            ImageIcon imageIcon = new ImageIcon(GameManager.icon);
            Image img = imageIcon.getImage();
            Image imgScale = img.getScaledInstance(jLabelImagen.getWidth(), jLabelImagen.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(imgScale);
            this.jLabelImagen.setIcon(scaledIcon);

        } catch (Exception e) {

            System.err.println("Error loading image for jLabelImagen: " + e.getMessage());

        }

        // CENTRAR EL BOTÓN EN EL PANEL
        this.jPanelBoton.setLayout(new FlowLayout(FlowLayout.CENTER));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new FondoPanel();
        jPanelMenu = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jLabelTitulo1 = new javax.swing.JLabel();
        jPanelBoton = new javax.swing.JPanel();
        jButtonStart = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxGame = new javax.swing.JCheckBox();
        jCheckBoxMusic = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BRICK BREACKER");
        setBackground(new java.awt.Color(51, 51, 255));
        setMinimumSize(new java.awt.Dimension(650, 650));
        setUndecorated(true);
        setPreferredSize(GameManager.pantalla);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });

        jPanelBackground.setBackground(new java.awt.Color(51, 0, 153));
        jPanelBackground.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanelBackground.setMinimumSize(new java.awt.Dimension(650, 650));
        jPanelBackground.setPreferredSize(new java.awt.Dimension(650, 650));

        jPanelMenu.setBackground(new Color(51,51,51, 150));
        jPanelMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelMenu.setMaximumSize(new java.awt.Dimension(600, 32767));
        jPanelMenu.setMinimumSize(new java.awt.Dimension(600, 640));
        jPanelMenu.setPreferredSize(new java.awt.Dimension(600, 640));

        jLabelImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon.png"))); // NOI18N
        jLabelImagen.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabelImagen.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabelImagen.setPreferredSize(new java.awt.Dimension(200, 200));

        jLabelTitulo1.setForeground(new java.awt.Color(204, 204, 204));
        jLabelTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo1.setText("BRICK BREACKER");
        jLabelTitulo1.setMaximumSize(new java.awt.Dimension(500, 50));
        jLabelTitulo1.setMinimumSize(new java.awt.Dimension(500, 50));
        jLabelTitulo1.setPreferredSize(new java.awt.Dimension(500, 50));

        jPanelBoton.setBackground(new Color(51,51,51, 200));
        jPanelBoton.setMinimumSize(new java.awt.Dimension(450, 100));
        jPanelBoton.setOpaque(false);
        jPanelBoton.setPreferredSize(new java.awt.Dimension(450, 100));

        jButtonStart.setBackground(new Color(32,28,55,50));
        jButtonStart.setForeground(new java.awt.Color(204, 204, 204));
        jButtonStart.setText("START");
        jButtonStart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonStart.setMargin(new java.awt.Insets(30, 14, 3, 14));
        jButtonStart.setMaximumSize(new java.awt.Dimension(55555, 5555));
        jButtonStart.setMinimumSize(new java.awt.Dimension(400, 60));
        jButtonStart.setOpaque(true);
        jButtonStart.setPreferredSize(new java.awt.Dimension(400, 60));
        jButtonStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonStartMouseExited(evt);
            }
        });
        jButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStartActionPerformed(evt);
            }
        });
        jButtonStart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonStartKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotonLayout = new javax.swing.GroupLayout(jPanelBoton);
        jPanelBoton.setLayout(jPanelBotonLayout);
        jPanelBotonLayout.setHorizontalGroup(
            jPanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jButtonStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelBotonLayout.setVerticalGroup(
            jPanelBotonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotonLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButtonStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setMaximumSize(new java.awt.Dimension(400, 60));
        jPanel3.setMinimumSize(new java.awt.Dimension(400, 60));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 60));

        jCheckBoxGame.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxGame.setText("Mute Game");
        jCheckBoxGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGameActionPerformed(evt);
            }
        });

        jCheckBoxMusic.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBoxMusic.setText("Mute Music");
        jCheckBoxMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMusicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jCheckBoxGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                .addComponent(jCheckBoxMusic)
                .addGap(16, 16, 16))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxGame)
                    .addComponent(jCheckBoxMusic))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jLabelTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jPanelBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStartActionPerformed

        this.frameFights = new JFrameFight(this);
        this.frameFights.startGame();

    }//GEN-LAST:event_jButtonStartActionPerformed

    private void jButtonStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStartMouseEntered

        this.jButtonStart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

    }//GEN-LAST:event_jButtonStartMouseEntered

    private void jButtonStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonStartMouseExited
        
    }//GEN-LAST:event_jButtonStartMouseExited

    private void jButtonStartKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonStartKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            this.jButtonStart.doClick();

        }

    }//GEN-LAST:event_jButtonStartKeyPressed

    private void jCheckBoxGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGameActionPerformed
        GameManager.stopSound = jCheckBoxGame.isSelected();

    }//GEN-LAST:event_jCheckBoxGameActionPerformed

    private void jCheckBoxMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMusicActionPerformed
        GameManager.stopMusic = jCheckBoxMusic.isSelected();
    }//GEN-LAST:event_jCheckBoxMusicActionPerformed

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        dispose();
    }//GEN-LAST:event_formWindowLostFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonStart;
    private javax.swing.JCheckBox jCheckBoxGame;
    private javax.swing.JCheckBox jCheckBoxMusic;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelTitulo1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelBoton;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables

}
